FROM rust:1.83 AS rust_dev_local

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        clang \
        clang-format \
        tar \
        lld \
        cmake \
        curl \
        git \
        pkg-config \
        libssl-dev \
        gdb \
	lldb \
    mkcert \
    certbot \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install sccache

ENV RUSTC_WRAPPER=sccache \
    CARGO_INCREMENTAL=0 \
    CARGO_BUILD_JOBS=default \
    RUSTFLAGS="-C debuginfo=2 -C link-arg=-fuse-ld=lld"

# docker build -t rust_dev_local:1_83 -f tools/CI/Dockerfile.rust_dev_local .