version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: tools/CI/Dockerfile.rust_dev_local
    container_name: api_dev
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "3001:3001"
    environment:
      - HTTPS_ADDR=0.0.0.0:3001
    command: |
      cargo run

  ui:
    build:
      context: ./ui
      dockerfile: tools/CI/Dockerfile.rust_wasm
    container_name: ui_dev
    working_dir: /app
    volumes:
      - ./ui:/app
    ports:
      - "8080:8080"
    environment:
      - API_ENDPOINT=https://localhost:3001
    command: |
      trunk serve --address 0.0.0.0 --port 8080
