FROM rust:1.72-bullseye

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        clang \
        clang-format \
        tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/
