[package]
name = "ui"
version = "0.0.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
gloo-net = "0.4" 
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["HtmlSelectElement"] }
gloo-timers = "0.3.0"

